### ISSUE TITLE
maxlikeSAR_run

### ISSUE THREAD

**Issue by hlos** [mortcanty/CRCENVI#1]
I would like to ask about the definition of variable 'm' in line 118 (it is not defined before that line).
I suppos that might be a mistake and there should be an expression 'cols*rows' like in the case desribed in lines: 106 - 114.
I would be grateful for any comments.

**Comment by hlos** [comment]
I would like to ask also about 'difference' function in line 149. 
In the IDL version that I use (IDL 8.4) this function is not recognized. 
I would be grateful for any comments.

**Comment by mortcanty** [comment]
Yes, this is an error, thanks. The variable m should be replaced by cols*rows.  I have commited the correction. 

The difference function (set difference) is defined in the AUXIL package, it is not an IDL function. The AUXIL directory must be in the IDL path for it to get picked up.

**Comment by hlos** [comment]
Thank you for answers. 

I would like to ask about the variable 'labels' in line 157. It is not defined before that line.

**Comment by mortcanty** [comment]
labels is an output variable. Please see the definitions of the argument MAX_SUBSCRIPT and the keyword DIMENSION in the IDL documentation.
